name: Echo Example
on: 
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
    - name: Show repository info
      run:
        echo $(date +'%Y-%m-%d')

