name: Echo time
on: 
  push: 
  schedule: 
    - cron: "* * * * *"
jobs:
  automated_test_1:
    name: Echo time
    runs-on: ubuntu-latest
    steps:
      - name: Show repository info
        run: echo $(date +'%Y-%m-%d')

